version: '3.3'
services:
  app:
    image: <TU-IMAGEN>
    environment:
      DBHOST: 'db'
      DBPASS: 'password'
      DBUSER: 'user'
      DBNAME: 'db'
    ports:
      - '8080:8080'
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: