version: '3.3'
services:
  app:
    image: "${APP_IMAGE_NAME}"
    restart: always
    environment:
      DBHOST: db
      DBPASS: 'password'
      DBUSER: 'user'
      DBNAME: 'db'
    ports:
      - '8090:8080'
    expose:
      - '8080'
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

# Names our volume
volumes:
  my-db: