name: cd

on:
  push:
    branches:
      - "nothing"

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Maven Package without test
        run: mvn -B clean package -DskipTests
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/<NOMBRE_DEL_PROYECTO>:${{ env.RELEASE_VERSION }}