name: deploy_aws_2

on:
  push:
    branches:
      - "main"
      - "master"
   
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials For GitHub Actions
        # You may pin to the exact commit or the version.
        # uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # The audience to use for the OIDC provider
          audience: # optional, default is sts.amazonaws.com
          # AWS Access Key ID. This input is required if running in the GitHub hosted environment. It is optional if running in a self-hosted environment that already has AWS credentials, for example on an EC2 instance.
          aws-access-key-id: # optional
          # AWS Secret Access Key. This input is required if running in the GitHub hosted environment. It is optional if running in a self-hosted environment that already has AWS credentials, for example on an EC2 instance.
          aws-secret-access-key: # optional
          # AWS Session Token
          aws-session-token: # optional
          # AWS Region, e.g. us-east-2
          aws-region: 
          # Whether to set the AWS account ID for these credentials as a secret value, so that it is masked in logs. Valid values are 'true' and 'false'. Defaults to true

