name: deploy-aws

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-aws:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: package w/o mvn-test
      run: mvn package -DskipTests
    